name: lint

on:
  push:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: dependencies
      run: |
           sudo apt install clang-tidy
           mkdir build
           cd build
           cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_COMPILER=clang++-14 -DCMAKE_C_COMPILER=clang-14
    - name: clang-tidy
      run: |
           chmod +x lint.sh
          #  ./lint.sh

           # Check that we're not merging the dev branch into main
           (grep 'LIBASSERT_CPPTRACE_TAG "origin/dev"' CMakeLists.txt && exit 1) || exit 0
